version: '3.8'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"


  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=change-me-in-prod
      - DATA_DIR=/data
    volumes:
      - ./:/usr/src/app
      # keep container's node_modules (avoid host mount hiding installed modules)
      - /usr/src/app/node_modules
      - app-data:/data
    depends_on:
      - redis

volumes:
  redis-data:
  app-data:
  
